name = "domain-finder-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV namespace for caching IANA bootstrap file
[[kv_namespaces]]
binding = "RDAP_CACHE"
id = "1107a48557d84bf2b9b745bbb924262e"
